### ISSUE TITLE
Compile the bundle

### ISSUE THREAD

**Issue by jamiedejong** [shaxxx/Xamarin.Vitamio#1]
Hey,

The problem with Vitamio is that it's not possible to have more streams than just one. So what I want to do is to compile this project to another namespace. This would be io2.vov.vitamio instead of io.vov.vitamio. Could you compile this for me? That would be amazing!

Because this should make it work to have 2 streams, which I need :+1:

**Comment by shaxxx** [comment]
Project is open sourced.

**Comment by jamiedejong** [comment]
Hey,

Yes I see, but I don't know how to compile the project to Xamarin Android.

Would you please do this for me?

Because I have no idea where to start (kinda noob in compiling)

Thanks!

Jamie
